sudo: required
language: ruby
rvm:
- 2.3.3
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: pNnw2XO+55Uv7coaq1o6Pdf0b1NCWi2bthVg7o2rAfZxgr32HBx0gIXLZs51TNKQm1LIjlw2KOqplI0bfv6jTd6Rm0SpE7HFc+uJe8eXRXdkgSGIKgLulyZYnU7JEr2AwG9JCffCu+KtBDrK9qqY/XdyZKRQpSVNa/qOn2lytDazFOc5pL+P/U1lXYYc2Xc3RiLYpK4fuA9EsCUBYvx7cJoCLK12Es1jYEf6l25kY11RvPHqBzHAopEmJ13LyHzJ+/x4CNwKkuAwjyGVob+15/UPbSuDCvzGnqIRQC8dIfnWCR3cNJ/0znOFpHTvBk8Pnz18fy/Jrc872adRY/ewyHrQvagEkPuCi897cAb/2pZO3Excfnr5JIOA4IkjyOgk5CzLjJy9wt8mPYxXXK93X/M3ZtwC5YSb2HggJzXICsOwQpJnS+oeYw758RI0bDps6jPJ3SyiDo3vpXRVYo+9Tq2Ynh4HYnf9N4yIAlqIzqL5qiBvfNxk4SMWIliYLFCtZ9DGMErJp9yeW7U0MJYlL8m0tWbTCfxWfh43N/6KqXNauHRWJMb7efJ8WyBBKW32iNVUfyorajTjrmmkaBgGg577Ew1jDvci5pAXM5inSAxAO9+sJiQzk3HJIQji77Vza/QZUCqmFqbtA3hNPO2WKJmXbzvnj4BFdJ79oB5tr0w=
  run:
  - rake db:migrate
  - restart
  app: enigmatic-bayou-52069
