sudo: required
language: ruby
rvm:
- 2.3.3
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: dUfqY+MvacpxhhatfElL/E+Sb+9HUdYzgZOd5FCOYVtEv99ksjZHvLTb5j8lQzcC6Uo7kH4NoX7cAy047HFQSgMqyp2nzVNzVmWV4O8gV8p5R/3nELfk9SgQKJWvOysk074RgfLFqiVhieQD+zJgsq7iWT4DV8Mcko8JUOajh0Ct1y3cjlWXhllGuJMx+9qbHzTwp11TvwWoa8hlEboOAbxN+sPMw5J4Ssfe5IW2rBuNfxbGrKOWriNBocArscaQm84Zn1EgbWnmh+6MoQ8H6FK3Bdz/H9GLnvrckxNlU2Oe5YkVexnk7EUs1kJC97SsJ3jKe43QJLCNEvxUnki4jqLuUOoVZnqQqIPLl1WVsNo05csBkJoTJEB9nqn0ZD8hzJv3h0cawUz4luZ8aphHNeULUduadHl4NTSDu242DtjFS1G4g92jJYduV4fDiAAnAAkvx0mcNl3Yw3pK+5Th8iT3OFe6XZK93UBfn800KMcKwS/aAuhyEAa4ikTRGbLvtGQhb+Xj2gkxUgHMW86pmu5ZP1NzfEbS2cSdnlmILNlPDfLQSKbsg1xv9oE5noBiA5XvcmWC9RxqsUhI2YfuC2i8I12fJ/l0T7FphDwRzQaJez9WxlGOcfkzfWAVsU1Ws7D3lXAPInVeYfEUULUfYu5NoVGXz0nCIFd2LRbOAlU=
  run:
  - rake db:migrate
  - restart
  app: the-addressbook
